name: Install ffmpeg

on: 
 workflow_dispatch:
jobs:
    install:
      runs-on: ubuntu-latest
      steps:
        - name: FFMPEG installation
          run: sudo apt update && install ffmpeg -y
        - name: run FFMPEG
          run: |
            ffmpeg --help
